name: List packages
on:
  push:
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: windows-2019
    steps:
      - name: install Chocolatey
        shell: cmd
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          choco source add -n=ros-win -s="https://aka.ms/ros/public" --priority=1
          choco list -s=ros-win --pre
