name: ROS2 in windows
on:
  push:
  workflow_dispatch:

jobs:
  build-packages:
    runs-on: windows-2019
    steps:
      - name: install Chocolatey
        shell: cmd
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          @"%SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"

      - name: install git
        shell: cmd
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          choco upgrade git -y --no-progress
          git --version

      - name: install ROS2 binaries
        shell: cmd
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          mkdir c:\opt\chocolatey
          set ChocolateyInstall=c:\opt\chocolatey
          choco source add -n=ros-win -s="https://aka.ms/ros/public" --priority=1
          choco upgrade ros-humble-desktop -y --execution-timeout=0 --pre --no-progress
        
      - name: test installation
        shell: cmd
        run: |
          call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          call c:\opt\ros\humble\x64\setup.bat
          ros2 wtf
